[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dynamo-utils"
version = "0.1.0"
description = "Utility for my discord bot"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.13"
dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["src/dynamo_utils"]

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "pytest>=8.3.3",
    "pytest-asyncio>=0.24.0",
    "ruff>=0.7.4",
]