name: CI

on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-22.04
    name: CI
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install project
        run: uv sync --all-extras --dev

      - name: Lint
        run: uv run ruff check --output-format github

      - name: Type Check
        run: uv run mypy src/

      - name: Test
        run: uv run pytest
        

      
